const TYPES = {
  HomeController: Symbol.for('HomeController'),
  InformationController: Symbol.for('InformationController'),
  TransactionController: Symbol.for('TransactionController'),
  UserController: Symbol.for('UserController'),
  ExchangeRateService: Symbol.for('ExchangeRateService'),
  InformationBalanceService: Symbol.for('InformationBalanceService'),
  InformationForecastService: Symbol.for('InformationForecastService'),
  InformationSeriesService: Symbol.for('InformationSeriesService'),
  InformationSummaryService: Symbol.for('InformationSummaryService'),
  TransactionFillService: Symbol.for('TransactionFillService'),
  TransactionPayService: Symbol.for('TransactionPayService'),
  TransactionWithdrawService: Symbol.for('TransactionWithdrawService'),
  UserLoginService: Symbol.for('UserLoginService'),
  UserLogoutService: Symbol.for('UserLogoutService'),
  UserSignupService: Symbol.for('UserSignupService'),
  CreateBlackListedTokenPort: Symbol.for('CreateBlackListedTokenPort'),
  CreateTransactionPort: Symbol.for('CreateTransactionPort'),
  CreateUserPort: Symbol.for('CreateUserPort'),
  LoadBalancePort: Symbol.for('LoadBalancePort'),
  LoadBlackListerTokenPort: Symbol.for('LoadBlackListerTokenPort'),
  LoadDailyExchangeRatesPort: Symbol.for('LoadDailyExchangeRatesPort'),
  LoadExchangeRatePort: Symbol.for('LoadExchangeRatePort'),
  LoadPaymentTransactionsPort: Symbol.for('LoadPaymentTransactionsPort'),
  LoadTransactionsByLastDaysPort: Symbol.for('LoadTransactionsByLastDaysPort'),
  LoadTransactionsByPeriodPort: Symbol.for('LoadTransactionsByPeriodPort'),
  LoadUserByEmailPort: Symbol.for('LoadUserByEmailPort'),
  LoadUserPort: Symbol.for('LoadUserPort'),
  SyncExchangeRatePort: Symbol.for('SyncExchangeRatePort'),
  BulkSaveExchangeRatePort: Symbol.for('BulkSaveExchangeRatePort'),
  ExchangeRateMapper: Symbol.for('ExchangeRateMapper'),
  TokenBlackListMapper: Symbol.for('TokenBlackListMapper'),
  TransactionMapper: Symbol.for('TransactionMapper'),
  UserMapper: Symbol.for('UserMapper'),
};

export { TYPES };
